Cherry pick of c761672d05bf22cd79460b85d5ee6d15506ca115 failed
stdout:

stderr:
17:51:27.534943 git.c:344               trace: built-in: git cherry-pick c761672d05bf22cd79460b85d5ee6d15506ca115
error: could not apply c761672d05b... [FIX] l10n_ar: AFIP currency rate.
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status: